/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpcommandes;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Thomas
 */
public class formCommande extends javax.swing.JFrame {

    /**
     * Creates new form formCommande
     */
    private DefaultListModel<Produit> listProds;
    private DefaultListModel<Commande> listCommandes;
    private DefaultListModel<Produit> listProdsCommande;
    
    public formCommande() {
        initComponents();
        
        listProds = new DefaultListModel<>();
        jListProduits.setModel(listProds);
        
        listCommandes = new DefaultListModel<>();
        jListCommandes.setModel(listCommandes);
        
        listProdsCommande = new DefaultListModel<>();
        jListProduitsCommande.setModel(listProdsCommande);
        
        listProds.addElement(new Produit("PlayStation 5", "PS5", 500));
        listProds.addElement(new Produit("Nintendo Switch", "NSW", 300));
        listProds.addElement(new Produit("Converse All Star", "CONV", 200));
        listProds.addElement(new Produit("Nike", "NI", 200));
        listProds.addElement(new Produit("Balanciaga", "BAL", 400));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAjouter = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProduits = new javax.swing.JList<>();
        btCreerCommande = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProduitsCommande = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCommandes = new javax.swing.JList<>();
        btSupprimer = new javax.swing.JButton();
        btCreerCommandeVIP = new javax.swing.JButton();
        txtReduc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAjouterACommande = new javax.swing.JButton();
        btnSupprimerProdDeCommande = new javax.swing.JButton();
        lbPanier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        jLabel1.setText("Prix");

        jLabel2.setText("Nom");

        jLabel3.setText("Code");

        jListProduits.setToolTipText("");
        jScrollPane1.setViewportView(jListProduits);

        btCreerCommande.setText("Créer commande");
        btCreerCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreerCommandeActionPerformed(evt);
            }
        });

        jListProduitsCommande.setToolTipText("");
        jScrollPane2.setViewportView(jListProduitsCommande);

        jListCommandes.setToolTipText("");
        jListCommandes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCommandesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListCommandes);

        btSupprimer.setText("Supprimer");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        btCreerCommandeVIP.setText("Créer commande VIP");
        btCreerCommandeVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreerCommandeVIPActionPerformed(evt);
            }
        });

        jLabel4.setText("Réduction (%)");

        btnAjouterACommande.setText("Ajouter");
        btnAjouterACommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterACommandeActionPerformed(evt);
            }
        });

        btnSupprimerProdDeCommande.setText("Supprimer");
        btnSupprimerProdDeCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerProdDeCommandeActionPerformed(evt);
            }
        });

        lbPanier.setText("Panier : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAjouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btSupprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtReduc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btCreerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btCreerCommandeVIP))
                                        .addComponent(lbPanier)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjouterACommande, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupprimerProdDeCommande, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(120, 120, 120)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCreerCommandeVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouterACommande)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimerProdDeCommande)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPanier)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(263, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void RAZ() {
        txtNom.setText("");
        txtCode.setText("");
        txtPrix.setText("");
    }
    
    private void actualiserCommande(Commande c) {
        listProdsCommande.clear();
            
            for (Produit p : c.getListProds()) {
                listProdsCommande.addElement(p);
            }
            
            jListProduitsCommande.setModel(listProdsCommande);
            lbPanier.setText("Panier total : " + c.getPrixTotal());
    }
    
    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txtCode.getText()) && !"".equals(txtNom.getText()) && !"".equals(txtPrix.getText())) {
            String code = txtCode.getText();
            String nom = txtNom.getText();
            int prix = Integer.parseInt(txtPrix.getText());
            
            Produit p = new Produit(nom,code,prix);
            listProds.addElement(p);
            //JOptionPane.showMessageDialog(this, "Le produit a bien été ajouté !");
        }
        RAZ();
    }//GEN-LAST:event_btAjouterActionPerformed

    private void btCreerCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreerCommandeActionPerformed
        // TODO add your handling code here:
        Commande c = new Commande(listCommandes.getSize()+1, LocalDate.now());
        listCommandes.addElement(c);
    }//GEN-LAST:event_btCreerCommandeActionPerformed

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        // TODO add your handling code here:
        if(jListProduits.getSelectedIndex() >= 0) {
            listProds.remove(jListProduits.getSelectedIndex());   
        }
    }//GEN-LAST:event_btSupprimerActionPerformed

    private void btCreerCommandeVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreerCommandeVIPActionPerformed
        // TODO add your handling code here:
        int reduc = Integer.parseInt(txtReduc.getText());
        Commande c = new CommandeVIP(listCommandes.getSize()+1, LocalDate.now(), reduc);
        listCommandes.addElement(c);
    }//GEN-LAST:event_btCreerCommandeVIPActionPerformed

    private void btnAjouterACommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterACommandeActionPerformed
        // TODO add your handling code here:*
        int indProd = jListProduits.getSelectedIndex();
        int indCmd = jListCommandes.getSelectedIndex();
        if(indProd >= 0 && indCmd >= 0) {
            Commande c = (Commande)listCommandes.get(indCmd);
            Produit p = (Produit)listProds.get(indProd);
            c.ajouterProduit(p);
            actualiserCommande(c);
        }
    }//GEN-LAST:event_btnAjouterACommandeActionPerformed

    private void btnSupprimerProdDeCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerProdDeCommandeActionPerformed
        // TODO add your handling code here:
        int indProd = jListProduits.getSelectedIndex();
        int indCmd = jListCommandes.getSelectedIndex();
        if(indProd >= 0 && indCmd >= 0) {
            Commande c = (Commande)listCommandes.get(indCmd);
            Produit p = (Produit)listProds.get(indProd);
            ArrayList<Produit> lP = c.getListProds();
            lP.remove(p);
            c.setListProds(lP);
            actualiserCommande(c);
        }
    }//GEN-LAST:event_btnSupprimerProdDeCommandeActionPerformed

    private void jListCommandesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCommandesValueChanged
        // TODO add your handling code here:
        int indCmd = jListCommandes.getSelectedIndex();
        if(indCmd >= 0) {
            Commande c = (Commande)listCommandes.get(indCmd);
            actualiserCommande(c);
        }
    }//GEN-LAST:event_jListCommandesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCommande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btCreerCommande;
    private javax.swing.JButton btCreerCommandeVIP;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JButton btnAjouterACommande;
    private javax.swing.JButton btnSupprimerProdDeCommande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Commande> jListCommandes;
    private javax.swing.JList<Produit> jListProduits;
    private javax.swing.JList<Produit> jListProduitsCommande;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbPanier;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtReduc;
    // End of variables declaration//GEN-END:variables
}
