INSERT INTO `type_monstre` (`CODE_TYPE_MONSTRE`, `NOM_TYPE_MONSTRE`) VALUES
('AQU', 'Aqua'),
('BTA', 'Bête-Ailée'),
('BTD', 'Bête Divine'),
('BTE', 'Bête'),
('BTG', 'Bête-Guerrier'),
('CYB', 'Cyberse'),
('DEM', 'Démon'),
('DIN', 'Dinosaure'),
('DRA', 'Dragon'),
('ELF', 'Elfe'),
('GUE', 'Guerrier'),
('INS', 'Insect'),
('MAC', 'Machine'),
('MAG', 'Magicien'),
('PLA', 'Plante'),
('POI', 'Poisson'),
('PSY', 'Psychique'),
('PYR', 'Pyro'),
('REP', 'Reptile'),
('ROC', 'Rocher'),
('SPM', 'Serpent de mer'),
('TNR', 'Tonnerre'),
('WYR', 'Wyrm'),
('ZOM', 'Zombie');
